import { useState } from "react";
import { useLocation, useNavigate, Link } from "react-router-dom";
import {
  ArrowLeft,
  Download,
  Copy,
  Check,
  FileText,
  RotateCcw,
  ChevronDown,
  ChevronUp,
  Quote,
  BarChart3,
  Clock,
  Hash,
  Tag,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import quantumLogo from "@/assets/quantum-logo.png";
import type { WhitePaperTemplate } from "@/lib/whitepaper-templates";

interface WhitePaperSection {
  id: string;
  name: string;
  content: string;
  pullQuote?: string;
  dataCallout?: { value: string; label: string };
}

interface WhitePaperData {
  title: string;
  subtitle: string;
  date: string;
  sections: WhitePaperSection[];
  metadata: {
    readingTime: string;
    wordCount: number;
    keyTopics: string[];
  };
}

const WhitePaperPreview = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { toast } = useToast();

  const whitepaper: WhitePaperData | null =
    location.state?.whitepaper || null;
  const template: WhitePaperTemplate | null =
    location.state?.template || null;

  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(whitepaper?.sections.map((s) => s.id) || [])
  );
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  if (!whitepaper || !template) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900 flex items-center justify-center">
        <div className="text-center space-y-4">
          <FileText className="w-16 h-16 text-cyan-400 mx-auto opacity-50" />
          <h2 className="text-xl font-semibold text-white">
            No white paper to preview
          </h2>
          <p className="text-slate-400 text-sm">
            Generate a white paper first to see the preview.
          </p>
          <Button
            onClick={() => navigate("/whitepaper")}
            className="bg-cyan-500 text-slate-900 hover:bg-cyan-400"
          >
            Go to Generator
          </Button>
        </div>
      </div>
    );
  }

  const toggleSection = (id: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const copySectionContent = (section: WhitePaperSection) => {
    navigator.clipboard.writeText(section.content);
    setCopiedSection(section.id);
    setTimeout(() => setCopiedSection(null), 2000);
    toast({
      title: "Section copied",
      description: `"${section.name}" content copied to clipboard.`,
    });
  };

  const copyFullDocument = () => {
    const fullText = [
      `# ${whitepaper.title}`,
      whitepaper.subtitle ? `## ${whitepaper.subtitle}` : "",
      `*${whitepaper.date}*`,
      "",
      ...whitepaper.sections.map(
        (s) => `## ${s.name}\n\n${s.content}`
      ),
    ]
      .filter(Boolean)
      .join("\n\n");

    navigator.clipboard.writeText(fullText);
    toast({
      title: "Full document copied",
      description: "Complete white paper content copied as markdown.",
    });
  };

  const downloadAsMarkdown = () => {
    const fullText = [
      `# ${whitepaper.title}`,
      whitepaper.subtitle ? `## ${whitepaper.subtitle}` : "",
      `*${whitepaper.date}*`,
      "",
      `*${whitepaper.metadata.readingTime} | ~${whitepaper.metadata.wordCount} words*`,
      "",
      ...whitepaper.sections.map((s) => {
        let block = `## ${s.name}\n\n${s.content}`;
        if (s.pullQuote) {
          block += `\n\n> ${s.pullQuote}`;
        }
        if (s.dataCallout) {
          block += `\n\n**${s.dataCallout.value}** — ${s.dataCallout.label}`;
        }
        return block;
      }),
      "",
      "---",
      `*Generated by The Quantum Insider | Template: ${template.name}*`,
    ]
      .filter(Boolean)
      .join("\n\n");

    const blob = new Blob([fullText], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${whitepaper.title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Download started",
      description: "White paper saved as markdown file.",
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-slate-900/90 backdrop-blur-lg border-b border-cyan-500/20">
        <nav className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-14">
            <Link to="/">
              <img src={quantumLogo} alt="TQI" className="h-7" />
            </Link>
            <div className="flex items-center gap-3">
              <Button
                variant="outline"
                size="sm"
                onClick={() => navigate("/whitepaper")}
                className="border-cyan-500/30 text-cyan-300 hover:bg-cyan-500/10 text-xs"
              >
                <RotateCcw className="w-3 h-3 mr-1" />
                New Document
              </Button>
              <Link
                to="/"
                className="flex items-center gap-2 text-cyan-300 hover:text-white text-sm"
              >
                <ArrowLeft className="w-4 h-4" />
                Framework
              </Link>
            </div>
          </div>
        </nav>
      </header>

      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 max-w-5xl">
        {/* Cover Section */}
        <div
          className="rounded-2xl p-8 md:p-12 mb-8 relative overflow-hidden"
          style={{ background: template.coverStyle.gradient }}
        >
          <div className="absolute inset-0 bg-black/20" />
          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-4">
              <img src={quantumLogo} alt="TQI" className="h-6 opacity-90" />
              <span className="text-white/60 text-xs font-medium uppercase tracking-wider">
                {template.name}
              </span>
            </div>
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 leading-tight">
              {whitepaper.title}
            </h1>
            {whitepaper.subtitle && (
              <p className="text-lg md:text-xl text-white/80 mb-6 max-w-3xl">
                {whitepaper.subtitle}
              </p>
            )}
            <div className="flex flex-wrap items-center gap-4 text-white/60 text-sm">
              <span>{whitepaper.date}</span>
              <span className="flex items-center gap-1">
                <Clock className="w-3.5 h-3.5" />
                {whitepaper.metadata.readingTime}
              </span>
              <span className="flex items-center gap-1">
                <Hash className="w-3.5 h-3.5" />~
                {whitepaper.metadata.wordCount.toLocaleString()} words
              </span>
            </div>
          </div>
        </div>

        {/* Metadata Bar */}
        <div className="flex flex-wrap items-center gap-2 mb-6">
          {whitepaper.metadata.keyTopics.map((topic) => (
            <span
              key={topic}
              className="flex items-center gap-1 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 text-xs"
            >
              <Tag className="w-3 h-3" />
              {topic}
            </span>
          ))}
        </div>

        {/* Action Bar */}
        <div className="flex flex-wrap gap-3 mb-8">
          <Button
            onClick={copyFullDocument}
            variant="outline"
            size="sm"
            className="border-cyan-500/30 text-cyan-300 hover:bg-cyan-500/10"
          >
            <Copy className="w-4 h-4 mr-2" />
            Copy All
          </Button>
          <Button
            onClick={downloadAsMarkdown}
            variant="outline"
            size="sm"
            className="border-cyan-500/30 text-cyan-300 hover:bg-cyan-500/10"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Markdown
          </Button>
        </div>

        {/* Sections */}
        <div className="space-y-4">
          {whitepaper.sections.map((section, idx) => (
            <div
              key={section.id}
              className="bg-slate-800/60 rounded-xl border border-cyan-500/20 overflow-hidden"
            >
              {/* Section Header */}
              <button
                onClick={() => toggleSection(section.id)}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-slate-800/80 transition-colors"
              >
                <div className="flex items-center gap-3">
                  {template.layoutStyle.headerStyle === "numbered" && (
                    <span className="w-7 h-7 rounded-full bg-cyan-500 text-slate-900 text-xs font-bold flex items-center justify-center flex-shrink-0">
                      {idx + 1}
                    </span>
                  )}
                  {template.layoutStyle.headerStyle === "gradient-bar" && (
                    <div className="w-1 h-6 rounded-full bg-gradient-to-b from-cyan-400 to-cyan-600 flex-shrink-0" />
                  )}
                  {template.layoutStyle.headerStyle === "underline" && (
                    <div className="w-4 h-0.5 bg-cyan-400 flex-shrink-0" />
                  )}
                  <h2 className="text-white font-semibold text-sm md:text-base">
                    {section.name}
                  </h2>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      copySectionContent(section);
                    }}
                    className="p-1.5 rounded-md hover:bg-cyan-500/20 text-slate-400 hover:text-cyan-300 transition-colors"
                  >
                    {copiedSection === section.id ? (
                      <Check className="w-4 h-4 text-green-400" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                  {expandedSections.has(section.id) ? (
                    <ChevronUp className="w-5 h-5 text-cyan-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-cyan-400" />
                  )}
                </div>
              </button>

              {/* Section Content */}
              {expandedSections.has(section.id) && (
                <div className="px-5 pb-5 border-t border-cyan-500/10">
                  <div
                    className={`pt-4 ${template.layoutStyle.columns === 2 ? "md:columns-2 md:gap-6" : ""}`}
                  >
                    {/* Data Callout */}
                    {section.dataCallout &&
                      template.layoutStyle.dataCallouts && (
                        <div className="bg-gradient-to-r from-cyan-500/10 to-transparent border-l-4 border-cyan-400 p-4 rounded-r-lg mb-4 break-inside-avoid">
                          <div className="flex items-center gap-2">
                            <BarChart3 className="w-5 h-5 text-cyan-400" />
                            <span className="text-2xl font-bold text-cyan-300">
                              {section.dataCallout.value}
                            </span>
                          </div>
                          <p className="text-sm text-slate-400 mt-1">
                            {section.dataCallout.label}
                          </p>
                        </div>
                      )}

                    {/* Main Content */}
                    <div className="prose prose-invert prose-sm max-w-none text-slate-300 leading-relaxed whitespace-pre-wrap">
                      {section.content.split("\n").map((line, lineIdx) => {
                        if (line.startsWith("### ")) {
                          return (
                            <h4
                              key={lineIdx}
                              className="text-white font-semibold text-sm mt-4 mb-2"
                            >
                              {line.replace("### ", "")}
                            </h4>
                          );
                        }
                        if (line.startsWith("## ")) {
                          return (
                            <h3
                              key={lineIdx}
                              className="text-white font-semibold text-base mt-4 mb-2"
                            >
                              {line.replace("## ", "")}
                            </h3>
                          );
                        }
                        if (line.startsWith("- ") || line.startsWith("* ")) {
                          return (
                            <li
                              key={lineIdx}
                              className="text-slate-300 text-sm ml-4 list-disc"
                            >
                              {line.replace(/^[-*] /, "")}
                            </li>
                          );
                        }
                        if (/^\d+\. /.test(line)) {
                          return (
                            <li
                              key={lineIdx}
                              className="text-slate-300 text-sm ml-4 list-decimal"
                            >
                              {line.replace(/^\d+\. /, "")}
                            </li>
                          );
                        }
                        if (line.startsWith("**") && line.endsWith("**")) {
                          return (
                            <p
                              key={lineIdx}
                              className="text-white font-semibold text-sm my-2"
                            >
                              {line.replace(/\*\*/g, "")}
                            </p>
                          );
                        }
                        if (line.trim() === "") {
                          return <br key={lineIdx} />;
                        }
                        return (
                          <p key={lineIdx} className="text-slate-300 text-sm mb-2">
                            {line}
                          </p>
                        );
                      })}
                    </div>

                    {/* Pull Quote */}
                    {section.pullQuote &&
                      template.layoutStyle.pullQuotes && (
                        <div className="mt-4 bg-cyan-500/5 border-l-4 border-cyan-500 p-4 rounded-r-lg break-inside-avoid">
                          <div className="flex gap-2">
                            <Quote className="w-5 h-5 text-cyan-400 flex-shrink-0 mt-0.5" />
                            <p className="text-cyan-200 text-sm italic leading-relaxed">
                              {section.pullQuote}
                            </p>
                          </div>
                        </div>
                      )}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 text-center py-6 border-t border-cyan-500/10">
          <p className="text-slate-500 text-xs">
            Generated by The Quantum Insider | Template: {template.name} |{" "}
            {whitepaper.date}
          </p>
          <p className="text-slate-600 text-xs mt-1">
            Powered by Resonance
          </p>
        </div>
      </main>
    </div>
  );
};

export default WhitePaperPreview;
